INSERT INTO A VALUES (1);
INSERT INTO B VALUES (1, '1', 1);
INSERT INTO B VALUES (2, '2', 1);
INSERT INTO B VALUES (3, '3', 1);

INSERT INTO A VALUES (2);
INSERT INTO B VALUES (4, '1', 2);

INSERT INTO A VALUES (3);
INSERT INTO B VALUES (5, '2', 3);
INSERT INTO B VALUES (6, '3', 3);

INSERT INTO A VALUES (4);
INSERT INTO B VALUES (7, '1', 4);
INSERT INTO B VALUES (8, '3', 4);

INSERT INTO A VALUES (5);
INSERT INTO B VALUES (9, '1', 5);

INSERT INTO A VALUES (6);

INSERT INTO A VALUES (7);
INSERT INTO B VALUES (10, '1', 7);
INSERT INTO B VALUES (11, '2', 7);
INSERT INTO B VALUES (12, '3', 7);

INSERT INTO A VALUES (8);

INSERT INTO A VALUES (9);
INSERT INTO B VALUES (13, '1', 9);

INSERT INTO A VALUES (10);
INSERT INTO B VALUES (14, '1', 10);
INSERT INTO B VALUES (15, '2', 10);
INSERT INTO B VALUES (16, '3', 10);

INSERT INTO A VALUES (11);
INSERT INTO B VALUES (17, '1', 11);
INSERT INTO B VALUES (18, '2', 11);

INSERT INTO A VALUES (12);
INSERT INTO B VALUES (19, '2', 12);
INSERT INTO B VALUES (20, '3', 12);

INSERT INTO A VALUES (13);

INSERT INTO A VALUES (14);
INSERT INTO B VALUES (21, '1', 14);

INSERT INTO A VALUES (15);
INSERT INTO B VALUES (22, '2', 15);

INSERT INTO A VALUES (16);
INSERT INTO B VALUES (23, '1', 16);

INSERT INTO A VALUES (17);
INSERT INTO B VALUES (24, '1', 17);
INSERT INTO B VALUES (25, '3', 17);

INSERT INTO A VALUES (18);
INSERT INTO B VALUES (26, '1', 18);
INSERT INTO B VALUES (27, '2', 18);
INSERT INTO B VALUES (28, '3', 18);

INSERT INTO A VALUES (19);

INSERT INTO A VALUES (20);
INSERT INTO B VALUES (29, '2', 20);